[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "96d6665b9392bbfb8f0fcee6998255cf5abde5c7"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "34954b3a9324756c555ccca213d6092b9d23c8e8146b1e2ce41dae73a49669ed"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.aarch64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "14d259fec366ba34a23357e07c8652a286b25f3e"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "edba6f1bc53c88ab740ef0e5ccbb0ac9d1e5ac0d68f1eb8152e0b8801864cc96"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.aarch64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "8e9b6f9a55cdf5428554dacf4bc3aa37f39d552a"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "cd2e3c6b4a5bc27a369434e0f5fece1e0959785ef990d0e37137b39373222cbe"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.aarch64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3255c08b24094bfa17402b3a921767e1fc50320f"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "2524a28b84d32861c89b8c120dcc1a9105891f552ba09b0525adf6522213ea7d"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.armv7l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a377d74a6c2f3ca728629dfca108c112d9446df7"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "259ca58d8eeed14bb699c839dde9b248002a8e7f87c20b91ce64307059ed7c30"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.armv7l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "3c5ab3ae8a8e038bc28d07be45384082e65ebad5"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "9db76b82180b9dd58659ba0a39d4bb9b6116aebe46922ece764d3d155c0e17f1"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.i686-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "f9759915d5790d5a6b0a164f4b14368ec121fc32"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "edefa8f273e326686e12a34e2d21b8b35356b71478eeb2bde21cc97eff53a670"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.i686-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "54972f39714054ce4d1a3a9a5ca030c9dfdb47b2"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "86274fd0e6f2130ed5034a32152ef8a55544e1eff1b0955fedb74d09436684b0"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.i686-w64-mingw32.tar.gz"
[[HarfBuzz]]
arch = "powerpc64le"
git-tree-sha1 = "3e8eb83d0f73772d1aa26af0db0173e499062a39"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "56d768ef767c1b6986be340c71ae56e5183f0e44fce22ba621acd5a65249ea64"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.powerpc64le-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "68f70f7c75d00042ac4e84d5c08dd63312080523"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "3f45b7ca6cb5d9e88dfa2ab92664a49467a15ccfd6b0ea7aef235d3b85487852"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.x86_64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "6c0abc86ba0cb373e3ced947f983fc935490c20d"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "93238c9eae3457f20add0ebc9682ec870b9ef287d939b5205aed7903fd17e646"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.x86_64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "46a334857c3dd4aa736c494a158da310529bf34d"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "89f6b6c68403ac38a234923e84fd28170fecb6fd2fa7549171efdc94ca5eec9a"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.x86_64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "65335d29608071a7e68867aa3be6625ada3d4a61"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "f62adfd47fc3f29fdaa04c6c235272d2548b0348e6ed79eea42225c95b3cdac2"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.x86_64-unknown-freebsd.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "ebb0a79b93dc14f7bf30514ee6c153c4f85bd6c9"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "2c5ab56733b9af687f5ee239990be83c2cbdb1cef70e9381d7197a8370b8c7ed"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+0/HarfBuzz.v2.8.1.x86_64-w64-mingw32.tar.gz"
