[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "995ff260ac1555fb27d71e40231aedb8ea0024ac"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "13b48c1835e8617e5033b752dfa91d275d29522e9bb94c178319e98c1725faae"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.aarch64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "01f2a78e40257f11ba5f4b6a168d4139246f5836"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "38a521ef7fe99c3e09d7fd5c197489ec175d3564a27053ec4e81bd41c4edee06"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.aarch64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "caea6cb0db318992203b3af486a9ca67024cd9c4"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "63fdbac2f0f12e836521daff84c878101cf46686883bd4ec1673f5f454fe37df"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.aarch64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "f129cbacffc7728a6530bf7d213a82c99b9fbdcb"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "479ea8ad014d013961421fc50554af329d7f24c37c832a7b9f055871f677803f"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.aarch64-unknown-freebsd.tar.gz"
[[HarfBuzz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e4792d37552e8614d27e1bb75f7a817bd5f838d"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "c9d087e6ddda9b4d46ae045c54d66b52f057a96f342622d8bb7fd2798f4b62a1"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.armv6l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dc6c7c4d225c3b8bcc6b61d21dbd24b96a02762d"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "270204cdeb380ff0bdb3add0973349c15305bed8023c628ec60fd8d0bad2211f"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.armv6l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86519a5a0c29bc4466c1058d0c37bae185930981"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "b8f090a700267d3d2330cda1c5d01a093636beb10fadcbb83748e6966a14e065"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.armv7l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0a9f969a0523f98c89b04937fa55500ef86922df"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "0f50aab4fd2b2d35a443eb4aa877f9fe27a0c2bd475b35b21a03d960fab5e171"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.armv7l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "2df38a07eade0968d7f7bf22c08d85b00cbf4152"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "2f0f23251c5de3bf84b26bb157bba5cf2e221b5d102f74778ba564830e5e34e4"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.i686-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "de5acb4af57415905a959e9418646ef761c40409"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "2410842bb26b4545b65479b779de2c11e57307f856e4528579341ad5ea7fbd45"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.i686-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "9b53f88450e2e4f39645e04d750f62a122205764"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "e8e36f086be9fca39090d16bfdc17f21ac9f686cf481380c9c599bad3b536929"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.i686-w64-mingw32.tar.gz"
[[HarfBuzz]]
arch = "powerpc64le"
git-tree-sha1 = "b3df630bac6252e21714b9bf573cc1b50bede9fc"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "54b858243a4b32275fc4abb1be23d9b4a42eae642c074b3f2c600f71325dce8b"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.powerpc64le-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "riscv64"
git-tree-sha1 = "dc7a5375685d5c28a36b7a21a4fed5611e2cadd4"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "949433c837f188ccb1da774eea69edd6dce8fe3cee927b75512ca605010cb78e"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.riscv64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "49d025a2ad932fc6617d2b0f8601b491c73f6078"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "33fbe46169102ef45f0d089265e94405ffbf9682003b0e555ba196862ce91625"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.x86_64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "bea36e542b11dd1475dc9719a813d8b341c7fd3a"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "34ce201aa64361e1f9ae051f7b9771f879973f8422613fe0c3f5117feb459e09"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.x86_64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "4619de7f762edc53eba0e0f12b45da2d98c8c111"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "04877dda74114e028f2c3c941cc6e88bc677c985c4182981f992f3c3689be60c"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.x86_64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "71b188b1d4c8a17eed4214409f4377c0116c9aec"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "2f8be33c128fa5629fc883daa59a00c94decd07660619e0b4ceafa5b2a39e3f0"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.x86_64-unknown-freebsd.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "683b7e8968bc7661913c3ffd3dd6d742fdaf5a65"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "df36c1dbc02f21fe20a355e30ea0be1d3ab98b687a4c2c72b4ba9f911fb76c06"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14004.0+0/HarfBuzz.v100.14004.0.x86_64-w64-mingw32.tar.gz"
