[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "a91151b59790a98a016de544604b5b0eed9163c9"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "e5a58196e6a7ff01674799bba1f51ac26700139b3a63f7d52eacf10547c3654c"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.aarch64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "2d4b42c92de26effc5df0d788e27a8c3eb85118d"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "0e566233f769e29fd2b27957c2cf68d7e41fb0b6be3379a9c951d80bfdce6a28"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.aarch64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "b536a4e3a031e71563379759650a4bcc9e4bb61f"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "2bd2e80881256c11555b24e9a3d7ca8c50bca1cefb666c8f482244bcbaaf236c"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.aarch64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "be97f18ce891f90021010b1828998fcdf10422fe"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "bce3c725ba4bdbba673bd24b09eb891d205ed786f6a8a38071bf92b592f57e4b"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.aarch64-unknown-freebsd.tar.gz"
[[HarfBuzz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cfb671de259df484227acadd00c7d64aaed5f66a"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "1955bd5ddff13acae51646e00438dde1374dc898fd72771120dffc3627df44bd"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.armv6l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dd772898056dd01d42a37b27c8c3b2eac16afdbb"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "5116956d90b4c3719cbee28f9f4921fd588b00295d8a3186c86703338bf4fd16"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.armv6l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da83711ef9bca2f74fb5d81820034fa534d69ddf"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "f4c2e454bc271040770c364182b067fc875255ab3bff5bd1aa07e3dcea41f212"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.armv7l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b5bb2201da23a736159087cbf34d536d10b666c4"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "d5e44d1aad8d8324378873083e02609cabbe0c47ffed60209bec43002f4098d0"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.armv7l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "eb62f0e881ee8d7dea702e39ab561ced0928007d"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "dbdcf203c24abd41e521635a64c61c13c03308839ba6c31d5903e7c9a3ef2763"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.i686-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "a15bc64424e86dab637e279421204b877cd0d119"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "d4b7a80bef371524ae766d524ea3c1c20536a7f3b14f7ccbb9e77647bbaad369"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.i686-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "bd58f782dac4ba8526db73836b7c33f95077fb5e"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "e7e9ebc450ba6ac672bbdf6b161b1d3bb355d88bddae9ed29a5cffae7e68136f"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.i686-w64-mingw32.tar.gz"
[[HarfBuzz]]
arch = "powerpc64le"
git-tree-sha1 = "e63631f789caea48dcf6ab987f6bdbfa429a9e2e"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "f3f8befe58b580916caf714a0c0224c18f2039065e491a8aecd118b029b25a1d"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.powerpc64le-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "riscv64"
git-tree-sha1 = "335bea245cdf0995ab59cee5f2e523e55382d530"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "848f4d14b008af36efb4c376541e7969a679c3df0250782be0f20ff6fe1695e6"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.riscv64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "a70c988ede4e8d705d485c6b497286b41c9d8708"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "ab48de47ca6e115a1b6e2f8dfd2960c00c3dd0f1b286230b32ef7440a2c67f1f"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.x86_64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "bff515f4c8e6db0fd9cf4d4421a4c5aa06872d76"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "064179694bf47e56a27896408edcfbe22013053d12b97ffcd79f100f0694d17e"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.x86_64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "dbba0afafcdc25b3c2d5315334a662efcb37db33"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "a3fb545d9e1e1a2eb6d0b8c92f7686509ad39b0dc21ec0ac061120159d0e6ad5"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.x86_64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "9f5a409068d0cab0319f01ebee8a26c175d681ad"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "5ed54e94d674b347bd0d65ed98f3b718a90a8790a886cb6bb425fbbf969222e2"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.x86_64-unknown-freebsd.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "94b12e22850b4f0f39951c028f1d27291e439361"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "4e6d356a05cae08d5f92339242fef6e5b8f248385e24267e569c8f16c6143ec9"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v100.14003.0+0/HarfBuzz.v100.14003.0.x86_64-w64-mingw32.tar.gz"
