[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "84c80d9b207b6d418d21833544896328887ebc37"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "b87b744bcc62691dba91e3718e45cc842d14ac70e41648ed113606656bba4083"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.aarch64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "28011ec10db85d6e790a31ae11a3ae464b2630a1"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "53078b01a9ee0959c374b150e025122c907c780363769821ec70f653a046924c"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.aarch64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
git-tree-sha1 = "6a48c9424239f24218661e1a262ba16e78d92f47"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "810f0442a9fe8bd99316fb51c5393fbff08955af66a555e992c473cd1498df70"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.armv7l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
git-tree-sha1 = "3f32f91388c61f802ce48bcbaecbfadb9893599f"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "4a8990fbf23c638ef051166d48062c7e089cfb77d3a5c72bf08f59121bbd0eb7"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.armv7l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "53d55500fbc1b991cdb13e60e3b16f081bace26e"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "d3328df7355fcee578381434a54e9c1cd52bd89a20ceebc8a47e6ced252ef0d6"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.i686-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "00b87f67fd44b087724cf25992ae909ff3afaf9d"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "2bd1940f26393209247357c55a0b9d1974b9245a4e1b3fbe28f2fe50574f556f"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.i686-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "0869c1f4617dcfed389cea26e70cb9ca44847ef4"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "47e103975f772e7696b82dc204eac9605d8bfd0c817f01a3b447d995251d7e50"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.i686-w64-mingw32.tar.gz"
[[HarfBuzz]]
arch = "powerpc64le"
git-tree-sha1 = "8afbea05cbbfc0fde532c3abce8701e0974cc0f9"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "fcd711508cc64c223f3e7afa65a449615256cb962de7cd284335b9f2b9bcb25b"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.powerpc64le-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "e7dd8c7a289c75e6621eb5183995743d6d24ea8b"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "e80466878ee914ca47519ab0b8c54f7148cfcb0ddc9bd38af232292c95d0a4da"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.x86_64-apple-darwin14.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "fde230b9c36a38332ec5f79f543ea95639b9002f"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "03f63367eb2a56af409a515ac610e73473a6636a302c382ccf05e1d8b8178733"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.x86_64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "37e77ddb9bad11d3f0473eda9caeecd734f4e29f"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "11f45785de2b72a4a79ac085910bb41bf7cfdd7d9b759a949273729ba81571b8"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.x86_64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "b120cf0187427bd14f66c7aee5add3b901cdfee3"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "8d6d2efe4c04e7f66505154e77eb656a16893a427297c18a5a6ad75ab3938d1f"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.x86_64-unknown-freebsd11.1.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "176d70a4003d15f3868b2fe4c28c0aafe8591b06"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "7f05e5d8be996b83e8df6d8fb3dba1f1c5dc24323b36c483bd30d56b44b6f3fd"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+6/HarfBuzz.v2.6.1.x86_64-w64-mingw32.tar.gz"
