[[HarfBuzz]]
arch = "armv7l"
git-tree-sha1 = "6746ad9326a7981e72f12aac069fb10f057b8344"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "6e01e3f270cb5140311eb8fb7c521880f4d6544e1064bc661a0aaaa122393471"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.arm-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "6c49f14b456d112fcce55fab77742e98b01f9144"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "8157bd6fa4a04a67ae3d06daffcbfca23d59daa59b7e146a000d45f9fc94a061"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.aarch64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "e11195d9237da593147bcd7695c81221868c5e7d"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "f3d3e71e57332a749f9ad4756da5e664e49f729cfd2136002465225ee3bafa17"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.i686-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "4de05e1852c27d67523615206e435d443a7294ef"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "8a276cd345ad0caf0bd8db7b171cb6e7d28ff016320d90b8e20d8988d9789942"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.i686-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "60ba2bc391eefe0cd4b3f52dba128acf918e7c5c"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "b3a52eff7b8779eeea832bdbbe5ded51c9c1603217b4c8c6a1e68989a93015ad"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.x86_64-unknown-freebsd11.1.tar.gz"
[[HarfBuzz]]
arch = "powerpc64le"
git-tree-sha1 = "ef645762fad1c0bb8f14b9849d318d6889bbb898"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "7eee80194565e6ff9c8a64b4885d881efc3d8d5052adfdf39a033576eddffbc4"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.powerpc64le-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
git-tree-sha1 = "5e9f0effedad8a711bfcefa7a1a4616c676af1fb"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "0cb99f0042a7ad10c4f3677367fc84811be46afba0703c5b2395f46b13b88930"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.arm-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "ba7670711b5417f6272dd0471af10e68513da8bd"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "bb08713e531d473962987ed0af017875fd9f45607cde5f0146f5e7332058c492"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.aarch64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "708cfd1d9a2608228098049c47c8a3db0a6d1f4a"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "0377d6b878c4738663159cc6cf367419f2c9fdfbc133d5ce71b0f477137a4229"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.x86_64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "56f7212b510418267ba73fc06e2d0539ee548b51"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "407bef391c31d1e3033f06d627690696f578cf1fabf11677c76e0ce7b9e25111"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.6.1+2/HarfBuzz.v2.6.1.x86_64-linux-musl.tar.gz"
